name: Build docker container

on:
  push:
    branches:
    - master
    - develop
    tags:
    - v*.*.*

jobs:
  build-image:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ${{ github.repository }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v2
    - name: Setup Docker BuildX
      uses: docker/setup-buildx-action@v2
      with:
        platforms: linux/amd64,linux/arm64
    # - name: Login in to Docker registry
    #   uses: docker/login-action@v2
    #   if: github.event_name != 'pull_request'
    #   with:
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Login in to Github registry
      uses: docker/login-action@v2
      if: github.event_name != 'pull_request'
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: |
          ghcr.io/${{ env.IMAGE_NAME }}
        tags: |
          type=schedule
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: '.'
        push: ${{ github.event_name != 'pull_request' }}
        file: ./Dockerfile
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/amd64,linux/arm64
